services:
  db:
    image: postgres
    container_name: book-review-db
    environment:
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_USER: 'admin'
      POSTGRES_DB: 'postgres'
  backend:
    build: ./backend
    volumes:
      - ./backend:/django
      - static_volume:/home/app/web/staticfiles
    ports:
      - 8000:8000
    image: app:django
    container_name: book-review-django
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
    volumes:
      - react_build:/react/dist
  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/react
      - static_volume:/home/app/web/staticfiles
    depends_on:
      - backend
      - frontend
volumes:
  react_build:
  static_volume: